---

# Wait for hass to startup and create some default config files.
# Once these files exist we can continue to modify one of them

- name: Wait for Hassio to be reachable over the network
  wait_for: 
    port: 8123
    delay: 10 

- name: Add configuration entries for PWN, sensors first.
  blockinfile:
    path: /home/pi/.homeassistant/configuration.yaml
    insertafter: "discovery:"
    content: |

      mqtt:
        broker: 192.168.42.254

- name: Add configuration entries for PWN, sensors first.
  blockinfile:
    path: /home/pi/.homeassistant/configuration.yaml
    insertafter: "sensor:"
    content: |
      # Controller 1
        - platform: mqtt
          name: Uptime Sensor controller_1
          state_topic: devices/controller_1/sensor/uptime_sensor_controller_1/state
          availability_topic: devices/controller_1/status
        - platform: mqtt
          name: WiFi Signal Sensor controller_1
          state_topic: devices/controller_1/sensor/wifi_signal_sensor_controller_1/state
          availability_topic: devices/controller_1/status
        - platform: mqtt
          name: Niveau Tank 1
          state_topic: devices/controller_1/sensor/niveau_tank_1/state
          availability_topic: devices/controller_1/status
          unit_of_measurement: '%'
      # Controller 2
        - platform: mqtt
          name: Uptime Sensor controller_2
          state_topic: devices/controller_2/sensor/uptime_sensor_controller_2/state
          availability_topic: devices/controller_2/status
        - platform: mqtt
          name: WiFi Signal Sensor controller_2
          state_topic: devices/controller_2/sensor/wifi_signal_sensor_controller_2/state
          availability_topic: devices/controller_2/status
        - platform: mqtt
          name: Flow door sensor controller_2
          state_topic: devices/controller_2/sensor/flow_door_sensor_controller_2/state
          availability_topic: devices/controller_2/status
          unit_of_measurement: l/m
      # Controller 3
        - platform: mqtt
          name: Uptime Sensor controller_3
          state_topic: devices/controller_3/sensor/uptime_sensor_controller_3/state
          availability_topic: devices/controller_3/status
        - platform: mqtt
          name: WiFi Signal Sensor controller_3
          state_topic: devices/controller_3/sensor/wifi_signal_sensor_controller_3/state
          availability_topic: devices/controller_3/status
        - platform: mqtt
          name: Niveau Tank 2
          state_topic: devices/controller_3/sensor/niveau_tank_2/state
          availability_topic: devices/controller_3/status
          unit_of_measurement: '%'
      # Controller 4
        - platform: mqtt
          name: Uptime Sensor controller_4
          state_topic: devices/controller_4/sensor/uptime_sensor_controller_4/state
          availability_topic: devices/controller_4/status
        - platform: mqtt
          name: WiFi Signal Sensor controller_4
          state_topic: devices/controller_4/sensor/wifi_signal_sensor_controller_4/state
          availability_topic: devices/controller_4/status
        - platform: mqtt
          name: Flow door sensor controller_4
          state_topic: devices/controller_4/sensor/flow_door_sensor_controller_4/state
          availability_topic: devices/controller_4/status
          unit_of_measurement: l/m
      # Contreller 5
        - platform: mqtt
          name: Uptime Sensor controller_5
          state_topic: devices/controller_5/sensor/uptime_sensor_controller_5/state
          availability_topic: devices/controller_5/status
        - platform: mqtt
          name: WiFi Signal Sensor controller_5
          state_topic: devices/controller_5/sensor/wifi_signal_sensor_controller_5/state
          availability_topic: devices/controller_5/status
        - platform: mqtt
          name: Niveau Tank 3
          state_topic: devices/controller_5/sensor/niveau_tank_3/state
          availability_topic: devices/controller_5/status
          unit_of_measurement: '%'


- name: Add configuration entries for PWN, switches next
  blockinfile:
    path: /home/pi/.homeassistant/configuration.yaml
    insertafter: "cloud:"
    content: |
      switch:
      # Controller 1
        - platform: mqtt
          name: Pomp 1
          state_topic: devices/controller_1/switch/pomp_1/state
          command_topic: devices/controller_1/switch/pomp_1/command
          availability_topic: devices/controller_1/status
          icon: mdi:skip-next
        - platform: mqtt
          name: Klep 1
          state_topic: devices/controller_1/switch/klep_1/state
          command_topic: devices/controller_1/switch/klep_1/command
          availability_topic: devices/controller_1/status
        - platform: mqtt
          name: Restart controller controller_1
          state_topic: devices/controller_1/switch/restart_controller_controller_1/state
          command_topic: devices/controller_1/switch/restart_controller_controller_1/command
          availability_topic: devices/controller_1/status
      # Controller 2
        - platform: mqtt
          name: Restart controller controller_2
          state_topic: devices/controller_2/switch/restart_controller_controller_2/state
          command_topic: devices/controller_2/switch/restart_controller_controller_2/command
          availability_topic: devices/controller_2/status
      # Controller 3
        - platform: mqtt
          name: Pomp 2
          state_topic: devices/controller_3/switch/pomp_2/state
          command_topic: devices/controller_3/switch/pomp_2/command
          availability_topic: devices/controller_3/status
          icon: mdi:skip-next
        - platform: mqtt
          name: Klep 2
          state_topic: devices/controller_3/switch/klep_2/state
          command_topic: devices/controller_3/switch/klep_2/command
          availability_topic: devices/controller_3/status
        - platform: mqtt
          name: Restart controller controller_3
          state_topic: devices/controller_3/switch/restart_controller_controller_3/state
          command_topic: devices/controller_3/switch/restart_controller_controller_3/command
          availability_topic: devices/controller_3/status
      # Controller 4
        - platform: mqtt
          name: Restart controller controller_4
          state_topic: devices/controller_4/switch/restart_controller_controller_4/state
          command_topic: devices/controller_4/switch/restart_controller_controller_4/command
          availability_topic: devices/controller_4/status
      # Controller 5
        - platform: mqtt
          name: Pomp 3
          state_topic: devices/controller_5/switch/pomp_3/state
          command_topic: devices/controller_5/switch/pomp_3/command
          availability_topic: devices/controller_5/status
          icon: mdi:skip-next
        - platform: mqtt
          name: Klep 3
          state_topic: devices/controller_5/switch/klep_3/state
          command_topic: devices/controller_5/switch/klep_3/command
          availability_topic: devices/controller_5/status
        - platform: mqtt
          name: Restart controller controller_5
          state_topic: devices/controller_5/switch/restart_controller_controller_5/state
          command_topic: devices/controller_5/switch/restart_controller_controller_5/command
          availability_topic: devices/controller_5/status

- name: Restart service hass after changing the config file
  systemd:
    state: restarted
    daemon_reload: yes
    name: hass
